// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_buffer_metrics_cpp
NumericMatrix compute_buffer_metrics_cpp(RawVector buffer, int n_frames, int n_pixels, IntegerVector subsample_idx, bool do_rgb, bool do_luminance, bool do_hsv, bool do_activity, bool do_spatial, int active_threshold, IntegerVector px_col, IntegerVector px_row, int n_metrics);
RcppExport SEXP _aniread_compute_buffer_metrics_cpp(SEXP bufferSEXP, SEXP n_framesSEXP, SEXP n_pixelsSEXP, SEXP subsample_idxSEXP, SEXP do_rgbSEXP, SEXP do_luminanceSEXP, SEXP do_hsvSEXP, SEXP do_activitySEXP, SEXP do_spatialSEXP, SEXP active_thresholdSEXP, SEXP px_colSEXP, SEXP px_rowSEXP, SEXP n_metricsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type buffer(bufferSEXP);
    Rcpp::traits::input_parameter< int >::type n_frames(n_framesSEXP);
    Rcpp::traits::input_parameter< int >::type n_pixels(n_pixelsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type subsample_idx(subsample_idxSEXP);
    Rcpp::traits::input_parameter< bool >::type do_rgb(do_rgbSEXP);
    Rcpp::traits::input_parameter< bool >::type do_luminance(do_luminanceSEXP);
    Rcpp::traits::input_parameter< bool >::type do_hsv(do_hsvSEXP);
    Rcpp::traits::input_parameter< bool >::type do_activity(do_activitySEXP);
    Rcpp::traits::input_parameter< bool >::type do_spatial(do_spatialSEXP);
    Rcpp::traits::input_parameter< int >::type active_threshold(active_thresholdSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type px_col(px_colSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type px_row(px_rowSEXP);
    Rcpp::traits::input_parameter< int >::type n_metrics(n_metricsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_buffer_metrics_cpp(buffer, n_frames, n_pixels, subsample_idx, do_rgb, do_luminance, do_hsv, do_activity, do_spatial, active_threshold, px_col, px_row, n_metrics));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aniread_compute_buffer_metrics_cpp", (DL_FUNC) &_aniread_compute_buffer_metrics_cpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_aniread(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
