# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute metrics for a buffer of frames
#'
#' Internal C++ worker called by [read_frame_metrics_full()]. Not intended for
#' direct use.
#'
#' @param buffer Raw vector containing one or more complete RGB24 frames.
#' @param n_frames Number of complete frames in `buffer`.
#' @param n_pixels Pixels per frame (`width * height`).
#' @param subsample_idx 1-based integer vector of pixel indices.
#' @param do_rgb,do_luminance,do_hsv,do_activity,do_spatial Logical flags.
#' @param active_threshold Integer luminance threshold (0--255).
#' @param px_col,px_row 1-based integer coordinate vectors, length `n_pixels`.
#'   Pass `integer(0)` when `do_spatial = FALSE`.
#' @param n_metrics Number of metric columns (excluding `time`).
#'
#' @return Numeric matrix with `n_frames` rows and `n_metrics` columns.
#'
#' @keywords internal
#' @export
compute_buffer_metrics_cpp <- function(buffer, n_frames, n_pixels, subsample_idx, do_rgb, do_luminance, do_hsv, do_activity, do_spatial, active_threshold, px_col, px_row, n_metrics) {
    .Call(`_aniread_compute_buffer_metrics_cpp`, buffer, n_frames, n_pixels, subsample_idx, do_rgb, do_luminance, do_hsv, do_activity, do_spatial, active_threshold, px_col, px_row, n_metrics)
}

